/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#002150",
        "tertiary-fixed-dim": "#61a6fb",
        "surface-dim": "#0a0e16",
        "on-background": "#e8eaf7",
        "error": "#ff716c",
        "on-primary-fixed-variant": "#002a62",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#5391ff",
        "on-tertiary-container": "#00284e",
        "primary-container": "#6e9fff",
        "secondary-dim": "#9ab6ef",
        "surface-container-low": "#0f131d",
        "on-surface": "#e8eaf7",
        "on-tertiary-fixed": "#001833",
        "surface-container": "#151a24",
        "background": "#0a0e16",
        "primary-fixed": "#6e9fff",
        "tertiary-container": "#64a8fe",
        "inverse-primary": "#005bc4",
        "tertiary": "#7fb6ff",
        "outline": "#727580",
        "primary-dim": "#699cff",
        "surface": "#0a0e16",
        "on-tertiary": "#003361",
        "on-error": "#490006",
        "on-primary": "#002c66",
        "surface-bright": "#262c39",
        "tertiary-fixed": "#7ab3ff",
        "surface-tint": "#85adff",
        "secondary": "#a7c4fe",
        "secondary-fixed-dim": "#a7c4fe",
        "on-secondary": "#1e3e6f",
        "inverse-surface": "#f9f9ff",
        "outline-variant": "#444852",
        "on-secondary-fixed-variant": "#335083",
        "surface-container-highest": "#202632",
        "on-surface-variant": "#a8abb6",
        "error-container": "#9f0519",
        "tertiary-dim": "#5ba0f5",
        "on-secondary-fixed": "#113364",
        "secondary-container": "#284678",
        "surface-container-high": "#1b202b",
        "primary": "#85adff",
        "surface-variant": "#202632",
        "secondary-fixed": "#bdd2ff",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed": "#000000",
        "error-dim": "#d7383b",
        "on-tertiary-fixed-variant": "#003a6c",
        "on-secondary-container": "#bbd1ff",
        "inverse-on-surface": "#51555f"
      },
      fontFamily: {
        "headline": ["Noto Serif", "Noto Sans Devanagari", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
